/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tictactoe;

import java.util.Random;
import java.util.Scanner;

public class App {

	public static void main(String[] args) {
		Tictactoe game = new Tictactoe();
		Scanner input = new Scanner(System.in);
		Random ia = new Random();

		while(game.winner  ==  null){

			game.nextPlayer();

			if(game.actualPlayer == "X"){

				System.out.println("--------------------------------------");
				game.printTable();

				RuntimeException error;
				do{
					error = null;
					System.out.print("Ingrese fila: ");
					int x = input.nextInt();
					System.out.print("Ingrese columna: ");
					int y = input.nextInt();
					try{
						game.play(x, y);
					}catch(RuntimeException e){
						error =e;

						System.out.println("Ingrese numeros validos!");
					}

				}while(error != null);

				
				game.checkWinner();
			}
			else if(game.actualPlayer == "O"){
				RuntimeException error;
				do{
					error = null;
					int x = ia.nextInt(3);
					int y = ia.nextInt(3);
					try{
						game.play(x+1, y+1);
					}catch(RuntimeException e){
						error =e;
					}

				}while(error != null);
				
				game.checkWinner();
			}
		}

		System.out.println("Gana " + game.winner + "!");

		input.close();
	}
}
